
/* 
     HTML DOM - Changing CSS

     The HTML DOM allows JavaScript to change the style of HTML elements.
     Syntax:
          document.getElementById(id).style.property = new style

    Using Events:
        The HTML DOM allows you to execute code when an event occurs.

    Events are generated by the browser when "things happen" to HTML elements:
          An element is clicked on
          The page has loaded
          Input fields are changed


*/    

document.getElementById("p2").style.color = "blue";
document.getElementById("p2").style.fontFamily = "Arial";
document.getElementById("p2").style.fontSize = "larger";

